apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-deployment-develop
  namespace: kubernetes-cluster-bhavinibatra
  labels:
    app: dotnet-app-develop
spec: 
  replicas: 4
  selector:
    matchLabels:
        app: dotnet-app-develop
  template:
    metadata:
        labels:
          app: dotnet-app-develop
    spec:
      containers:
        - name: dotnet-app-develop
          image: bhavinibatra/develop:latest
          ports:
            -  name: http
               containerPort: 80
               protocol: TCP
---
apiVersion: v1
kind: Service
metadata: 
    name: dotnet-app-develop
    namespace: kubernetes-cluster-bhavinibatra
spec: 
   type: NodePort
   selector:
       app: dotnet-app-develop
   ports:
      - protocol: TCP
        nodePort: 30158
        port: 80
        targetPort: 80
