apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-deployment-test-develop
  labels:
    app: dotnet-app-test-develop
spec: 
  replicas: 3
  selector:
    matchLabels:
        app: dotnet-app-test-develop
  template:
    metadata:
        labels:
          app: dotnet-app-test-develop
    spec:
      containers:
        - name: dotnet-app-test-develop
          image: bhavinibatra/test-develop:latest
          ports:
            -  name: http
               containerPort: 80
               protocol: TCP
---
apiVersion: v1
kind: Service
metadata: 
    name: dotnet-app-test-develop
spec: 
   type: NodePort
   selector:
       app: dotnet-app-test-develop
   ports:
      - protocol: TCP
        nodePort: 30151
        port: 80
        targetPort: 80